### ISSUE TITLE
Retrieve all records

### ISSUE THREAD

**Issue by david-fiaty** [nmaggioni/Simple-JSONdb#22]
Hello, super great module.
At the moment there is no way to retrieve all records from the database.
I've extended the core with a getAll() method, which seems to work as expected.
```
JSONdb.prototype.getAll = function() {
  return this.storage;
}; 
```
Please let me know if it's ok to create a pull request on the master branch to add this method.
Thanks a lot

**Comment by nmaggioni** [comment]
Did you look into [`db.JSON()`](https://github.com/nmaggioni/Simple-JSONdb/blob/ccf1d7d48af708919a8c1e8328853578ffaf0e38/index.js#L171)? Handling the internal object directly bypasses the rest of the wrappers and could potentially lead to corrupt states, which is all this little toy library offers over manually dumping an object to disk.

**Comment by david-fiaty** [comment]
Sorry mate, db.JSON() doesn't return anything, and there are no errors either. However when I extend the core with the function above, it returns my stored data seamlessly.

**Comment by david-fiaty** [comment]
My coode is very simple, here it is:
```
const JSONdb = require('simple-json-db');
const path = require('path');
const db = new JSONdb(path.join(__dirname, '../storage.json'));

// Get all values
JSONdb.prototype.getAll = function () {
  return this.storage;
};

module.exports = {
  /*
   * Insert data in database
   */
  insert: (rows) => {
    for (let [k, v] of Object.entries(rows)) {
      db.set(k, v);
    }
  },

  /*
   * Select data from database
   */
  select: (key) => {
    key == key || null;
    return (key) ? db.get(key) : db.getAll(); // => here, using db.JSON() doesn't work
  },
}
```
Unless I missed something in the doc, db.JSON() has an issue. Side note, db.set() works perfectly.

**Comment by nmaggioni** [comment]
```js
select: (key) => {
  key == key || null;
  return (key) ? db.get(key) : db.getAll();
}
```

Ignoring the comparison instead of the assignment in the second row (you are actually just executing `true || null` and discarding its result here), the third row will never work as intended because you are simply checking if the `key` string is [truthy](https://developer.mozilla.org/en-US/docs/Glossary/Truthy). That means that with any truthy argument the first branch of that comparison will always be executed and as such `db.get(key)` [correctly returns `undefined`](https://github.com/nmaggioni/Simple-JSONdb/blob/master/index.js#L110) for non-existing keys.

So please remember to double check your code for common errors before blaming the issue on any library you'll be using in the future. On the other hand I've just added a test for the `.JSON()` call (f34944f), so thanks for making me notice it was missing.

**Comment by david-fiaty** [comment]
You are absolutely right. Thanks a lot.
