### ISSUE TITLE
Compatibility with Electron

### ISSUE THREAD

**Issue by david-fiaty** [nmaggioni/Simple-JSONdb#23]
I'm trying to use simple-JSONdb with electron. Data is properly stored as expected when I run the node app. However if I package the node app as a .exe using electron-forge, all features are lost. There are no errors, but the storage just doesn't work. Is there something I could do about this issue?

**Comment by nmaggioni** [comment]
If you are using code similar to what I saw in #22, remember that most packagers are not compatible with relative paths or require special approaches to make them work. Your data is probably getting saved in a temporary directory and subsequently deleted.

Closing as not pertinent to this project since the unpackaged app works, please refer to electron-forge's upstream for further support.

**Comment by david-fiaty** [comment]
ok thank you
